apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    type: backend
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: db
        type: backend
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
          - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      type: backend