apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    type: backend
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: db
        type: backend
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
          - containerPort: 5432
          env:
            - name: "POSTGRESQL_DATABASE"
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: database-name
            - name: "POSTGRESQL_USER"
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database-user
            - name: "POSTGRESQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database-password
  replicas: 1
  selector:
    matchLabels:
      type: backend